<?php

/**
 * @file stripe.module
 * Drupal hooks used for integrating the Stripe service.
 */

/**
 * Implements hook_help().
 */
function stripe_help($path, $arg) {
  if ($path == 'admin/config/stripe/admin/keys') {
    $output = '<ol>';
    $output .= '<li>' . t('Enter the API keys you get from your <a href="@url">Stripe account page</a>.', array('@url' => 'https://manage.stripe.com/account')) . '</li>';
    $output .= '<li>' . t('Use the radio buttons to choose which API Key should be used with this site.') . '</li>';
    $output .= '<li>' . t('After designating an API Key, you might want to try out <a href="@url">the test form</a>.', array('@url' => '/admin/config/stripe/test')) . '</li>';
    $output .= '</ol>';
    return $output;
  }
  if ($path == 'admin/config/stripe/admin/test') {
    return '<p>' . t('This form is to test responses from Stripe. The default values are accepted by Stripe for testing purposes. Before you can use this form, you should <a href="@url">designate an active API Key</a>.', array('@url' => '/admin/config/stripe/keys')) . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function stripe_permission() {
  return array(
    'administer stripe' => array(
      'title' => t('Administer the Stripe module'),
      'description' => t('Allows access to configure API Keys and to the test form.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function stripe_menu() {
  $items['admin/config/stripe'] = array(
    'title' => 'Stripe Payment Gateway',
    'description' => 'Configuration, and testing',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer stripe'),
    'position' => 'right',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/stripe/keys'] = array(
    'title' => 'API Keys',
    'description' => 'Enter API Keys and set which one should be active.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stripe_admin_keys'),
    'access arguments' => array('administer stripe'),
    'file' => 'stripe.admin.inc',
  );

  $items['admin/config/stripe/test'] = array(
    'title' => 'Test form',
    'description' => 'A form for testing Stripe responses.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stripe_admin_test'),
    'access arguments' => array('administer stripe'),
    'file' => 'stripe.test.inc',
  );

  return $items;
}

/**
 * Implements hook_requirements().
 */
function stripe_requirements($phase) {
  $requirements = array();
  if ($phase == 'runtime') {
    $requirements['stripe'] = _stripe_requirement_check();
  }
  return $requirements;
}

/**
 * Helper function to hook_requirements.
 */
function _stripe_requirement_check() {
  $t = get_t();
  if (file_exists('sites/all/libraries/stripe/lib/Stripe.php')) {
    return array(
      'title' => $t('Stripe Payment API PHP Library'),
      'value' => $t('Stripe PHP Library is in place. Version @version', array('@version' => file_get_contents('sites/all/libraries/stripe/VERSION'))),
      'severity' => REQUIREMENT_OK,
    );
  }
  else {
    return array(
      'title' => $t('Stripe Payment API PHP Library'),
      'value' => $t('The Stripe PHP Library is not in place. <a href="https://code.stripe.com/stripe-php-latest.zip">Download the and unzip the library</a> then place the contents of that directory in sites/all/libraries/stripe'),
      'severity' => REQUIREMENT_ERROR,
    );
  }
}

/**
 * Helper function to go fetch the normal form elements.
 */
function stripe_form_default_items() {
  $form = array();
  $form['card_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Card Number'),
    '#size' => 16,
    '#attributes' => array(
      'autocomplete' => 'off',
      'class' => array('card-number'),
    ),
  );

  $form['card_cvc'] = array(
    '#type' => 'textfield',
    '#title' => t('CVC'),
    '#size' => 4,
    '#attributes' => array(
      'autocomplete' => 'off',
      'class' => array('card-cvc'),
    ),
  );

  // Will be re-enabled by javascript. This ensures that the element cannot be
  // used unless javascript is fully functioning.
  $form['card_number']['#disabled'] =
     $form['card_cvc']['#disabled'] = TRUE;
  // Remove the #name field before rendering, so that this element will not
  // get posted back to the server.
  $form['card_number']['#pre_render'] =
     $form['card_cvc']['#pre_render'] = array('stripe_element_remove_name');
  // Ensure the element is empty when submitted.
  $form['card_number']['#element_validate'] =
     $form['card_cvc']['#element_validate'] = array('stripe_element_validate_empty');


  $form['card_expiry_month'] = array(
    '#type' => 'select',
    '#title' => t('Expiration Month'),
    '#attributes' => array(
      'class' => array('card-expiry-month'),
    ),
    '#multiple' => FALSE,
    '#options' => array(
      '01' => t('01 (Jan)'),
      '02' => t('02 (Feb)'),
      '03' => t('03 (Mar)'),
      '04' => t('04 (Apr)'),
      '05' => t('05 (May)'),
      '06' => t('06 (Jun)'),
      '07' => t('07 (Jul)'),
      '08' => t('08 (Aug)'),
      '09' => t('09 (Sep)'),
      '10' => t('10 (Oct)'),
      '11' => t('11 (Nov)'),
      '12' => t('12 (Dec)'),
    ),
  );

  $current_year = date('Y');
  $years = range($current_year, $current_year + 15);
  $year_options = array_combine($years, $years);

  $form['card_expiry_year'] = array(
    '#type' => 'select',
    '#title' => t('Expiration Year'),
    '#attributes' => array(
      'class' => array('card-expiry-year'),
    ),
    '#options' => $year_options,
  );

  // The stripe JS will populate this value upon successful submission.
  $form['stripe_token'] = array(
    '#type' => 'hidden',
  );

  if ($pub_key = stripe_get_publishable_key()) {
    // Attach the javascript from Stripe.
    $form['#attached']['js'] = array(
      'https://js.stripe.com/v1/' => array(
        'type' => 'external',
      ),
      drupal_get_path('module', 'stripe') . '/stripe.js',
      // And set our key.
      'jQuery(document).ready(function () { Stripe.setPublishableKey("' . $pub_key . '"); });' => array(
        'type' => 'inline', 'scope' => 'footer', 'weight' => 5
      ),
    );
  }

  return $form;
}

/**
 * Element validate function to ensure that the posted value for an element is
 * empty. We do this just to double check that credit card numbers are not
 * getting posted to the server, as this would create PCI implications. If they
 * are making it back to the server, we stop the form from processing, and log a
 * watchdog alert.
 */
function stripe_element_validate_empty($element, $form_state, $form) {
  static $logged = FALSE;
  // Log a watchdog message the first time only. No need to log two messages.
  if (!empty($element['#value']) && !$logged) {
    // Set an error on the first element this happened on.
    form_error($element, 'There was a problem processing your payment. For '   .
                         'your own protection, it is recommended you do NOT '  .
                         'attempt to re-enter your payment information.');
    // Now log a watchdog alert.
    $message = 'Credit Card information is being posted to your server. '      .
               'Please disable Stripe module immediately and submit a bug '    .
               'report at http://drupal.org/node/add/project-issue/stripe.';
    watchdog('stripe', $message, NULL, WATCHDOG_ALERT);
    $logged = TRUE;
  }
}

/**
 * Pre render callback for Stripe elements with sensitive information, to remove
 * the 'name' attribute. This ensures that the browser doesn't post the values
 * back to the server.
 */
function stripe_element_remove_name($element) {
  unset($element['#name']);
  return $element;
}

/**
 * Initialize the Stripe PHP Library with the configured secret key.
 */
function stripe_initialize() {
  $inited = &drupal_static(__FUNCTION__);

  // No need to do anything if we've already initialized.
  if (isset($inited)) {
    return;
  }

  require_once("sites/all/libraries/stripe/lib/Stripe.php");

  $status = variable_get('stripe_key_status', 'test');
  $secret_key_name = 'stripe_' . $status . '_secret';
  $secret_key = variable_get($secret_key_name, '');

  empty($secret_key) ? NULL : Stripe::setApiKey($secret_key);
  $inited = TRUE;
}

/**
 * Get the Stripe publishable key.
 */
function stripe_get_publishable_key() {
  $status = variable_get('stripe_key_status', 'test');
  $pub_key_name = 'stripe_' . $status . '_publishable';
  $pub_key = variable_get($pub_key_name, '');
  return $pub_key;
}
